[package]
name = "istanco_ddns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
dns-lookup = "1.0.8"
dotenv = "0.15.0"
reqwest = { version = "0.11.16", features = ["cookies"] }
scraper = "0.16.0"
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros"] }
